### ISSUE TITLE
Update to 1.1.2 introduces database schema changes, not reflected in documentation

### ISSUE THREAD

**Issue by alienmindbender** [modoboa/modoboa-admin#42]
Version 1.1.2 expects a different database schema at least in the admin_alias table, than in the previous version. This is not reflected in the documentation. The upgrade breaks single functions of the administration interface if applied without a database update.

Maybe I'am just messing up the upgrade procedure! I tried setting up a new instance with "modoboa-admin.py deploy" as mentioned in the documentation (using the same database). This fails with several errors cause of existing mysql table entries.
I also tried "python manage.py migrate modoboa_admin" as mentioned in modoboa-admins readme - failing with similar errors.

So whats the proper way to upgrade an existing installation?

**Comment by tonioo** [comment]
The upgrade procedure is globally the same than for previous versions (http://modoboa.readthedocs.org/en/latest/getting_started/upgrade.html)

You can also apply migrations manually:
```shell
$ python manage.py migrate
```

You will also need to update your postfix configuration (http://modoboa.org/en/weblog/2015/10/21/new-releases/)

**Comment by alienmindbender** [comment]
Thanks - I missed that step.
Maybe it should be included in the docs under "Upgrading an existing installation". Right now I can only a find a reference under "Specific upgrade instructions --> 1.3.0".
I'll have a closer look to the blog in the future :)

However, I still have an error excuting "python manage.py migrate" when upgrading modoboa_postfix_autoreply to version 1.1.1:


```
Operations to perform:
  Apply all migrations: core, modoboa_admin, lib, sessions, reversion, modoboa_postfix_autoreply, auth, sites, contenttypes, modoboa_imap_migration, modoboa_admin_limits
Running migrations:
  Applying modoboa_postfix_autoreply.0002_auto_20150728_1236... OK
  Applying modoboa_postfix_autoreply.0003_move_aliases...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 105, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/special.py", line 117, in database_forwards
    self.code(from_state.render(), schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/modoboa_postfix_autoreply/migrations/0003_move_aliases.py", line 18, in move_aliases
    AliasRecipient.objects.bulk_create(to_create)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 409, in bulk_create
    self._batched_insert(objs_without_pk, fields, batch_size)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 938, in _batched_insert
    using=self.db)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 921, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 176, in execute
    if not self._defer_warnings: self._warning_check()
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 92, in _warning_check
    warn(w[-1], self.Warning, 3)
_mysql_exceptions.Warning: Data truncated for column 'address' at row 69
```
Since it's the wrong section you probably want to close this one and I open another issue for the specific plugin?

**Comment by tonioo** [comment]
Yes please.
